{
 "title": "Grow Rooms",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "room",
    "label": "Room",
    "query": "SHOW TAG VALUES WITH KEY = \"raum_nummer\""
   },
   {
    "name": "lotnr",
    "label": "LotNr",
    "query": "SHOW TAG VALUES WITH KEY = \"lot_nummer\""
   },
   {
    "name": "measurement_T",
    "query": "SHOW MEASUREMENTS WITH MEASUREMENT =~ /_T/"
   },
   {
    "name": "measurement_H",
    "query": "SHOW MEASUREMENTS WITH MEASUREMENT =~ /_H/ OFFSET 4"
   }
  ]
 },
 "panels": [
  {
   "title": "Info",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Die beiden Panel der Shellys (Feuchtigkeit & Temperatur) zeigen immer nur den Wert aller zuvor ausgewählten Shellys aus\nUm die Wert der gewünschten Shellys auszuwählen kann im Feld measurement_T = Temperature oder measurement_H = Humidity eine Auswahl getroffen werden.         "
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Shellys", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Temperatur",
   "type": "graph",
   "description": "Values of selected Shellys (measurement_T)",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$measurement_T$/",
     "query": "SELECT mean(\"value\") FROM \"Shellyht101_T\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Actual Temperature measurement_T",
   "type": "stat",
   "description": "Last Value of selected Shellys (measurement_T)",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$measurement_T$/",
     "query": "SELECT mean(\"value\") FROM \"Shellyht101_T\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Feuchtigkeit",
   "type": "graph",
   "description": "Values of selected Shellys (measurement_H)",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 4 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$measurement_H$/",
     "query": "SELECT mean(\"value\") FROM \"Shellyht101_T\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Actual Humidity measurement_H",
   "type": "stat",
   "description": "Last Value of selected shellys (measurement_H)",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$measurement_H$/",
     "query": "SELECT mean(\"value\") FROM \"Shellyht101_T\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Gicom", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Lufttemperatur / Luftklappe",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "celsius", "label": "Temperature" }
   ],
   "targets": [
    {
     "alias": "Lufttemperatur (Raum $tag_raum_nummer)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "raum_nummer" ], "type": "tag" }
     ],
     "measurement": "gicom",
     "select": [
      [
       { "params": [ "lufttemp_grad_celsius" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "raum_nummer", "operator": "=~", "value": "/^$room$/" },
      { "condition": "AND", "key": "lot_nummer", "operator": "=~", "value": "/^$lotnr$/" }
     ]
    },
    {
     "alias": "Luftklappe (Raum $tag_raum_nummer)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "raum_nummer" ], "type": "tag" }
     ],
     "measurement": "gicom",
     "select": [
      [
       { "params": [ "luftklappe_prozent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "raum_nummer", "operator": "=~", "value": "/^$room$/" },
      { "condition": "AND", "key": "lot_nummer", "operator": "=~", "value": "/^$lotnr$/" }
     ]
    }
   ]
  },
  {
   "title": "Co2 Konzentration",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "ppm", "label": "Co2 Concentration" }
   ],
   "targets": [
    {
     "alias": "Co2 (Raum $tag_raum_nummer)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "raum_nummer" ], "type": "tag" }
     ],
     "measurement": "gicom",
     "select": [
      [
       { "params": [ "co2_ppm" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "raum_nummer", "operator": "=~", "value": "/^$room$/" },
      { "condition": "AND", "key": "lot_nummer", "operator": "=~", "value": "/^$lotnr$/" }
     ]
    }
   ]
  },
  {
   "title": "Dampf",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "percent", "label": "Dampf" }
   ],
   "targets": [
    {
     "alias": "Dampf (Raum $tag_raum_nummer)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "raum_nummer" ], "type": "tag" }
     ],
     "measurement": "gicom",
     "select": [
      [
       { "params": [ "dampf_prozent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "raum_nummer", "operator": "=~", "value": "/^$room$/" },
      { "condition": "AND", "key": "lot_nummer", "operator": "=~", "value": "/^$lotnr$/" }
     ]
    }
   ]
  }
 ]
}